import { AnimationProps } from './utils'

export const DEFAULT_ANIMATIONS: Record<
  string,
  Omit<AnimationProps, 'name' | 'duration'> & { duration: number }
> = {
  moveToLeft: {
    duration: 600,
    timing: 'ease',
    fill: 'both',
  },
  moveFromLeft: {
    duration: 600,
    timing: 'ease',
    fill: 'both',
  },
  moveToRight: {
    duration: 600,
    timing: 'ease',
    fill: 'both',
  },
  moveFromRight: {
    duration: 600,
    timing: 'ease',
    fill: 'both',
  },
  moveToTop: {
    duration: 600,
    timing: 'ease',
    fill: 'both',
  },
  moveFromTop: {
    duration: 600,
    timing: 'ease',
    fill: 'both',
  },
  moveToBottom: {
    duration: 600,
    timing: 'ease',
    fill: 'both',
  },
  moveFromBottom: {
    duration: 600,
    timing: 'ease',
    fill: 'both',
  },
  fade: {
    duration: 600,
    timing: 'ease',
    fill: 'both',
  },
  moveToLeftFade: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
  },
  moveFromLeftFade: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
  },
  moveToRightFade: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
  },
  moveFromRightFade: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
  },
  moveToTopFade: {
    duration: 600,
    timing: 'ease',
    fill: 'both',
  },
  moveFromTopFade: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
  },
  moveToBottomFade: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
  },
  moveFromBottomFade: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
  },
  scaleDown: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
  },
  scaleUp: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
  },
  scaleUpDown: {
    duration: 500,
    timing: 'ease',
    fill: 'both',
  },
  scaleDownUp: {
    duration: 500,
    timing: 'ease',
    fill: 'both',
  },
  scaleDownCenter: {
    duration: 400,
    timing: 'ease',
    fill: 'both',
  },
  scaleUpCenter: {
    duration: 400,
    timing: 'ease',
    fill: 'both',
  },
  rotateRightSideFirst: {
    duration: 800,
    timing: 'ease-in',
    fill: 'both',
    origin: '0% 50%',
  },
  rotateLeftSideFirst: {
    duration: 800,
    timing: 'ease-in',
    fill: 'both',
    origin: '0% 50%',
  },
  rotateTopSideFirst: {
    duration: 800,
    timing: 'ease-in',
    fill: 'both',
    origin: '0% 50%',
  },
  rotateBottomSideFirst: {
    duration: 800,
    timing: 'ease-in',
    fill: 'both',
    origin: '0% 50%',
  },
  flipOutRight: {
    duration: 500,
    timing: 'ease-in',
    fill: 'both',
    origin: '50% 50%',
  },
  flipInLeft: {
    duration: 500,
    timing: 'ease-out',
    fill: 'both',
    origin: '50% 50%',
  },
  flipOutLeft: {
    duration: 500,
    timing: 'ease-in',
    fill: 'both',
    origin: '50% 50%',
  },
  flipInRight: {
    duration: 500,
    timing: 'ease-out',
    fill: 'both',
    origin: '50% 50%',
  },
  flipOutTop: {
    duration: 500,
    timing: 'ease-in',
    fill: 'both',
    origin: '50% 50%',
  },
  flipInBottom: {
    duration: 500,
    timing: 'ease-out',
    fill: 'both',
    origin: '50% 50%',
  },
  flipOutBottom: {
    duration: 500,
    timing: 'ease-in',
    fill: 'both',
    origin: '50% 50%',
  },
  flipInTop: {
    duration: 500,
    timing: 'ease-out',
    fill: 'both',
    origin: '50% 50%',
  },
  rotateFall: {
    duration: 1000,
    timing: 'ease-in',
    fill: 'both',
    origin: '0% 0%',
  },
  rotateOutNewspaper: {
    duration: 500,
    timing: 'ease-in',
    fill: 'both',
    origin: '50% 50%',
  },
  rotateInNewspaper: {
    duration: 500,
    timing: 'ease-out',
    fill: 'both',
    origin: '50% 50%',
  },
  rotatePushLeft: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '0% 50%',
  },
  rotatePushRight: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '100% 50%',
  },
  rotatePushTop: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '50% 0%',
  },
  rotatePushBottom: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '50% 100%',
  },
  rotatePullRight: {
    duration: 500,
    timing: 'ease',
    fill: 'both',
    origin: '100% 50%',
  },
  rotatePullLeft: {
    duration: 500,
    timing: 'ease',
    fill: 'both',
    origin: '0% 50%',
  },
  rotatePullTop: {
    duration: 500,
    timing: 'ease',
    fill: 'both',
    origin: '50% 0%',
  },
  rotatePullBottom: {
    duration: 500,
    timing: 'ease',
    fill: 'both',
    origin: '50% 100%',
  },
  rotateFoldRight: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
    origin: '0% 50%',
  },
  rotateFoldLeft: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
    origin: '100% 50%',
  },
  rotateFoldTop: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
    origin: '50% 100%',
  },
  rotateFoldBottom: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
    origin: '50% 0%',
  },
  rotateUnfoldLeft: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
    origin: '100% 50%',
  },
  rotateUnfoldRight: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
    origin: '0% 50%',
  },
  rotateUnfoldTop: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
    origin: '50% 100%',
  },
  rotateUnfoldBottom: {
    duration: 700,
    timing: 'ease',
    fill: 'both',
    origin: '50% 0%',
  },
  rotateRoomLeftOut: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '100% 50%',
  },
  rotateRoomLeftIn: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '0% 50%',
  },
  rotateRoomRightOut: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '0% 50%',
  },
  rotateRoomRightIn: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '100% 50%',
  },
  rotateRoomTopOut: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '50% 100%',
  },
  rotateRoomTopIn: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '50% 0%',
  },
  rotateRoomBottomOut: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '50% 0%',
  },
  rotateRoomBottomIn: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '50% 100%',
  },
  rotateCubeLeftOut: {
    duration: 600,
    timing: 'ease-in',
    fill: 'both',
    origin: '100% 50%',
  },
  rotateCubeLeftIn: {
    duration: 600,
    timing: 'ease-in',
    fill: 'both',
    origin: '0% 50%',
  },
  rotateCubeRightOut: {
    duration: 600,
    timing: 'ease-in',
    fill: 'both',
    origin: '0% 50%',
  },
  rotateCubeRightIn: {
    duration: 600,
    timing: 'ease-in',
    fill: 'both',
    origin: '100% 50%',
  },
  rotateCubeTopOut: {
    duration: 600,
    timing: 'ease-in',
    fill: 'both',
    origin: '50% 100%',
  },
  rotateCubeTopIn: {
    duration: 600,
    timing: 'ease-in',
    fill: 'both',
    origin: '50% 0%',
  },
  rotateCubeBottomOut: {
    duration: 600,
    timing: 'ease-in',
    fill: 'both',
    origin: '50% 0%',
  },
  rotateCubeBottomIn: {
    duration: 600,
    timing: 'ease-in',
    fill: 'both',
    origin: '50% 100%',
  },
  rotateCarouselLeftOut: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '100% 50%',
  },
  rotateCarouselLeftIn: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '0% 50%',
  },
  rotateCarouselRightOut: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '0% 50%',
  },
  rotateCarouselRightIn: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '100% 50%',
  },
  rotateCarouselTopOut: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '50% 100%',
  },
  rotateCarouselTopIn: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '50% 0%',
  },
  rotateCarouselBottomOut: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '50% 0%',
  },
  rotateCarouselBottomIn: {
    duration: 800,
    timing: 'ease',
    fill: 'both',
    origin: '50% 100%',
  },
  rotateSidesOut: {
    duration: 500,
    timing: 'ease-in',
    fill: 'both',
    origin: '-50% 50%',
  },
  rotateSidesIn: {
    duration: 500,
    timing: 'ease-in',
    fill: 'both',
    origin: '150% 50%',
  },
  rotateSlideOut: {
    duration: 1000,
    timing: 'ease',
    fill: 'both',
  },
  rotateSlideIn: {
    duration: 1000,
    timing: 'ease',
    fill: 'both',
  },
} as const
